version: "3.7"

services:
  app:
    build: ./app
    volumes:
      - ./app:/app
    ports:
      - "8000:8000"
    links:
      - redis:redis
    depends_on:
      - redis
    logging:
      driver: gelf
      options:
        gelf-address: "tcp://localhost:9600"
        tag: "galaxyrangers-eua"

  app2:
    build: ./app2
    volumes:
      - ./app2:/app2
    ports:
      - "8002:8002"
    links:
      - redis:redis
    depends_on:
      - redis
    logging:
      driver: gelf
      options:
        gelf-address: "tcp://localhost:9600"
        tag: "silverhawks"

  redis:
    image: "redis:alpine"
    expose:
      - "6379"
    depends_on:
      - logstash
    logging:
      driver: gelf
      options:
        gelf-address: "tcp://localhost:9600"
        tag: "redis"

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.2.1
    volumes:
      - ./elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
    ports:
      - "9200:9200/tcp"
      - "9300:9300/tcp"
    environment:
      ES_JAVA_OPTS: "-Xmx1024m -Xms1024m"
    networks:
      - elk

  logstash:
    dns:
      - 10.18.248.81
    image: docker.elastic.co/logstash/logstash:7.2.1
    volumes:
      - ./logstash/pipeline/pipelines.conf:/usr/share/logstash/pipeline/pipelines.conf
      - ./logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml
    ports:
      - "5001:5001/tcp"
      - "9600:9600/tcp"
    environment:
      LS_JAVA_OPTS: "-Xmx256m -Xms256m"
    networks:
      - elk
    depends_on:
      - elasticsearch

  kibana:
    image: docker.elastic.co/kibana/kibana:7.2.1
    volumes:
      - ./kibana/config:/usr/share/kibana/config
    ports:
      - "5601:5601/tcp"
    networks:
      - elk
    depends_on:
      - elasticsearch

networks:
  elk:
    driver: bridge